"use client";

import { motion } from "framer-motion";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { LightbulbIcon } from "lucide-react";

const faqs = [
  {
    question: "How does Zeroface.ai work?",
    answer: "Zeroface.ai uses AI-driven automation to transform your ideas or scripts into polished, faceless videos. Simply provide a concept—whether it’s a fictional text chat, a Reddit-style story, or a split-screen comparison—and our platform handles voiceovers, visuals, captions, and editing.",
  },
  {
    question: "Do I need video editing skills or prior experience?",
    answer: "Not at all. Our AI takes care of the production process from start to finish, so you can create professional, monetizable videos without ever learning complex editing tools.",
  },
  {
    question: "What types of videos can I create?",
    answer: "You can produce a variety of faceless content—from fake text conversation shorts and Reddit-inspired narratives to split-screen gaming comparisons. These formats are ideal for TikTok, YouTube Shorts, Instagram Reels, and other short-form platforms.",
  },
  {
    question: "How quickly can I start earning money?",
    answer: "With Zeroface.ai, you can generate engaging content within few weeks. Pairing our built-in monetization strategies with your AI-created videos helps you start earning sooner, potentially reaching up to $10,000 monthly.",
  },
  {
    question: "Is the content generated by Zeroface.ai safe and royalty-free?",
    answer: "Yes. All AI-generated material is royalty-free and safe for commercial use. Just be sure any additional third-party assets you include are licensed correctly.",
  },
  {
    question: "Can Zeroface.ai help me find profitable niches?",
    answer: "Absolutely. Our targeted niche analysis tools guide you toward high-potential markets, letting you focus on creating the content that drives engagement and revenue.",
  },
  {
    question: "What about pricing and plans?",
    answer: "We offer a free tier so you can test things out, plus premium plans with advanced features, higher-quality outputs, and expert-level monetization guidance. Upgrade whenever you’re ready to scale up.",
  },
  {
    question: "I have more questions!",
    answer: "We’re here to help. Contact us through our support form or email us at support@zeroface.ai, and we’ll gladly assist with any additional inquiries.",
  },
];

export default function FAQ() {
  return (
    <section className="py-16 md:py-24 px-4 bg-background">
      <div className="container mx-auto max-w-4xl">
        <div className="flex items-center justify-center gap-2 mb-4">
          <LightbulbIcon className="w-5 h-5 text-primary" />
          <span className="text-primary font-medium">FAQ</span>
        </div>
        <motion.h2 initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-center mb-8 sm:mb-12">
          Your questions, answered.
        </motion.h2>
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.2 }}>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="border rounded-lg px-4 sm:px-6 data-[state=open]:bg-muted/50">
                <AccordionTrigger className="text-left hover:no-underline text-sm sm:text-base">{faq.question}</AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-sm">{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
}
